import { UserProvider } from "../../models/UserContext";
import "./globals.css";

export const metadata = {
  title: "Pro Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
